### ISSUE TITLE
Choose a single var style?

### ISSUE THREAD

**Issue by localpcguy** [EnlightenAgency/EnlBase#10]
```
var asfd;
var fdsa;
```

vs

```
var asdf,
    fdsa;
```

**Comment by localpcguy** [comment]
First way:
Pros: less errors when declaring or removing variable declarations, easier to read 
Cons: more typing, potentially encourages variables to be defined where used, rather than at the top.

Second way:
Pros: single var statement, encourages variables to all be defined in the same block.
Cons: easy to accidentally create a global variable when adding/removing variables from the block

**Comment by kmaida** [comment]
I've been using the first way more and more these days and I like it (and it results in making fewer mistakes as a result of missing commas or extra semicolons). My vote is for the first way.

**Comment by localpcguy** [comment]
I also prefer the first way and have been using it lately.

**Comment by mmager** [comment]
I prefer the first way as well. Less room for errors and just cleaner IMO.

**Comment by kmaida** [comment]
Disallow multiple variable declaration.
