### ISSUE TITLE
Create Angular documentation?

### ISSUE THREAD

**Issue by kmaida** [EnlightenAgency/EnlBase#16]
Since we are having more and more people implementing Angular components, should we create a section for Angular documentation and styles?

**Comment by localpcguy** [comment]
Do we think our standards would deviate significantly from the John Papa styleguide? If not, we could have a brief section summarizing that and point to it for further (more specific) reading.

**Comment by kmaida** [comment]
I think there are a couple of key differences (ie, never using `vm` as a variable name), but overall, not significantly. Then again, I haven't checked the styleguide thoroughly lately, so I probably need to refresh briefly before I can say more on that.

**Comment by kmaida** [comment]
[update] I've done a deep-dive into the John Papa styleguide recently and we are accepting it as our official standard. My only complaints with it have actually been revised by John Papa himself (and the contributing community) since I had last looked at it. :)
