### ISSUE TITLE
Include mgchev in angular style guide resources

### ISSUE THREAD

**Issue by DamianEnlighten** [EnlightenAgency/EnlBase#17]
https://github.com/mgechev/angularjs-style-guide

This was the style guide I used myself at Locqus.

**Comment by localpcguy** [comment]
I like this, I feel like, compared to the JP guide, this may be more approachable guide to start someone with no Angular experience on. I'll still recommend we base most of our decisions on the John Papa guide, particularly if the guide's are in conflict, but it looks like a nice resource. Maybe we can create a new Wiki for resources for learning X technology, and start a list of helpful resources there.

And this guide appears to be very accepting of requests for updates, so we could potentially suggest updates to things we think we can improve.

**Comment by kmaida** [comment]
I agree with Mike, and want to add that the John Papa styleguide is what we've _officially_ standardized on, but having additional resources for reference is always welcome. Like Mike said, the mgchev guide covers some of the introductory basics of Angular development that John Papa doesn't. That will be very useful to fill in some gaps in documentation.

As of now, our Angular section in the standards documentation is sparse (I'm sure you've noticed). I'll be fleshing it out quite  a bit more as we head into our next big Angular initiative in the upcoming weeks, and I'll add the mgchev guide to a list of resources. Thanks!

**Comment by localpcguy** [comment]
updated the wiki to add a resources section for Angular JS, including both the John Papa styleguide as the main source and the mgchev link as a secondary resource
